### ISSUE TITLE
Set up API access

### ISSUE THREAD

**Issue by aviaowl** [useme-com/revolut-python#1]
Hi @emesik !

I'm going to use this library for developing my own application with access to Revolut.
It seems a little bit unclear in README.md how to set up API access for my account.
Can you please clarify where I can find this:

> In Revolut panel go to Settings / API and click Set up API access.

I can see nothing like this in my Revolut application or in my Revolut developer account.

Thank you in advance

**Comment by emesik** [comment]
I see they have changed the layout. Log into the business account via web, then click "Connect" in the left sidebar and choose "Business API". I hope the rest of the process will work.

If you manage to set it up, a PR with necessary changes in the doc would be very welcome. Otherwise don't hesitate to ask further questions.

**Comment by emesik** [comment]
Seems fixed.
